# Generated by Django 3.0.9 on 2020-08-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('level_no', models.IntegerField(default=0)),
                ('target', models.FloatField(default=0.0)),
                ('Ac_No', models.IntegerField(default=0)),
                ('bank', models.CharField(max_length=200)),
                ('IFSC', models.CharField(max_length=11)),
                ('Pan_no', models.CharField(max_length=10)),
            ],
        ),
    ]
